# -*- coding: utf-8 -*-
"""Students Social Media Addiction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upEUnq9g6eywJm4rvt6u9F04qEPAxpPb
"""

pimport pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data= pd.read_csv("/content/Students Social Media Addiction.csv")

#Display dataset
print(data)

#Shape
print(data.shape)

#Columns
print(data.columns)

#Data types
print(data.dtypes)

#missing values
print(data.isnull().sum())

#Duplicate Rows
print(data.duplicated())

print(data.duplicated().sum())

#Average age of users
print("Average Age:", data['Age'].mean())

#Average daily usage hours
print("Average Daily Usage Hours:", data['Avg_Daily_Usage_Hours'].mean())

#Which platform is most used
print(data['Most_Used_Platform'].value_counts())

print("Most Used Platform:", data['Most_Used_Platform'].mode()[0])

#Male vs Female average daily usage
print(data.groupby('Gender')['Avg_Daily_Usage_Hours'].mean())

#Mental Health Score vs Average Daily Usage
print(data.groupby('Mental_Health_Score')['Avg_Daily_Usage_Hours'].mean())

#Sleep Hours vs Addicted Score
print(data.groupby('Sleep_Hours_Per_Night')['Addicted_Score'].mean())

#Academic Performance vs Daily Usage
print(data.groupby('Affects_Academic_Performance')[ 'Avg_Daily_Usage_Hours'].mean())

#Which age group uses social media the most?
age_usage = data.groupby('Age')['Avg_Daily_Usage_Hours'].mean()

print(age_usage)

print("Age with Highest Usage:", age_usage.idxmax())

#Top 10 addicted users
top10 = data.sort_values(by='Addicted_Score', ascending=False).head(10)

print(top10)

#Platform-wise average usage
print(data.groupby('Most_Used_Platform')['Avg_Daily_Usage_Hours'].mean())

#Average addiction score
print("Average Addiction Score:", data['Addicted_Score'].mean())

#Most Used Platform
plt.figure(figsize=(8,5))
data['Most_Used_Platform'].value_counts().plot(kind='bar')
plt.title("Most Used Social Media Platform")
plt.xlabel("Platform")
plt.ylabel("Number of Users")
plt.show()

#Gender Distribution
plt.figure(figsize=(6,6))
data['Gender'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

#Age Distribution
plt.figure(figsize=(8,5))
plt.hist(data['Age'], bins=10)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

#Daily Usage Hours
plt.figure(figsize=(6,5))
sns.boxplot(y=data['Avg_Daily_Usage_Hours'])
plt.title("Daily Usage Hours")
plt.show()

#Sleep Hours vs Addiction Score
plt.figure(figsize=(8,5))
plt.scatter(
    data['Sleep_Hours_Per_Night'],
    data['Addicted_Score']
)
plt.title("Sleep Hours vs Addiction Score")
plt.xlabel("Sleep Hours")
plt.ylabel("Addicted Score")
plt.show()

#Academic Level
plt.figure(figsize=(8,5))
sns.countplot(x='Academic_Level', data=data)
plt.title("Academic Level Distribution")
plt.xlabel("Academic Level")
plt.ylabel("Count")
plt.show()